import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from './components/navbar/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Next',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            {/* Add bg white for remaining part */}
            <body
                suppressHydrationWarning={true}
                className={'flex flex-col min-h-screen max-w-screen-max m-auto'}
            >
                <Navbar />
                {children}
            </body>
        </html>
    );
}
